// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygftukmfmyiqmlnznzje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlnZnR1a21mbXlpcW1sbnpuemplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNDU3NjQsImV4cCI6MjA3MjgyMTc2NH0.qIWuebgsbakQR_uhLy3-U_IzJmJLD5wT-pboMCoVWs8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});